{% set name = "sentineleof" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c7e715659b4c1e68568a99943c5e22c46681289658079e9421bdc3a9d92aee5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eof = eof.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests
    - python-dateutil
    - click

test:
  imports:
    - eof
  commands:
    - eof --help

about:
  home: https://github.com/scottstanie/sentineleof
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Precise orbit file download for Sentinel 1
  description: |
    Tool to download Sentinel 1 precise/restituted orbit files (.EOF files)
    for processing SLCs
  dev_url: https://github.com/scottstanie/sentineleof

extra:
  recipe-maintainers:
    - avalentino
    - scottstanie
