{% set name = "sentineleof" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c10632d63c3aa9b0f2f0205f6ef8fea9818f4a514f22a297705ba03beed14cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eof = eof.cli:cli

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - requests
    - python-dateutil
    - click

test:
  imports:
    - eof
  requires:
    - pytest
    - responses
  commands:
    - eof --help
    - python -m pytest -v --pyargs eof

about:
  home: https://github.com/scottstanie/sentineleof
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Precise orbit file download for Sentinel 1
  description: |
    Tool to download Sentinel 1 precise/restituted orbit files (.EOF files)
    for processing SLCs
  dev_url: https://github.com/scottstanie/sentineleof

extra:
  recipe-maintainers:
    - avalentino
    - scottstanie
