{% set name = "sentineleof" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e77dd9ae1ebc8c89db2665045cb44c8e43cd58ce2675991cfa5eb30b2dde7a63

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eof = eof.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - python-dateutil
    - click

test:
  requires:
    - python {{ python_min }}
  imports:
    - eof
  commands:
    - eof --help

about:
  home: https://github.com/scottstanie/sentineleof
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Precise orbit file download for Sentinel 1
  description: |
    Tool to download Sentinel 1 precise/restituted orbit files (.EOF files)
    for processing SLCs
  dev_url: https://github.com/scottstanie/sentineleof

extra:
  recipe-maintainers:
    - avalentino
    - scottstanie
